name: Version & Release

on:
  push:
    branches:
      - master

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    container:
      image: rightbrainnetworks/auto-semver
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run Auto-Semver
      id: semver
      uses: RightBrain-Networks/semver-action@1.0.0
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: steps['semver']['outputs']['RETURN_STATUS'] == '0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
        release_name: ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
        body: Release Version ${{ steps.semver.outputs.SEMVER_NEW_VERSION }}
        draft: false
        prerelease: false